### ISSUE TITLE
[public utility] [ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate (default) on project api-facturacion: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate: com/sun/xml/bind/api/ErrorListener

### ISSUE THREAD

**Issue by callmezarri** [jahe/spring-boot-multiple-datasources#2]
if you have problems with IDEA and OpenJDK, especially the snap package, to solve it you have to change the default JRE of your system, in ubuntu it is possible to do it using

sudo update-alternatives --config java

and then select the option shown below

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

**Comment by jahe** [comment]
Hi @callmezarri!
Thanks for opening an issue. Whats the point of your issue?

As a guideline use the following template to specify your description:

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**Which versions of Java, Spring, and which OS are affected by this issue? Did this work in previous versions of Java or Spring?**

**Comment by callmezarri** [comment]
the purpose of this issue is to help people who have the same problem, in the company where I work is a very common problem and i hope it help others
